development:
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin
  pool_size: 5
  timeout: 5
  db_name: shapado-development
test:
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin  
  pool_size: 5
  timeout: 5
production:
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin  
  pool_size: 5
  timeout: 5
  db_name: shapado-development