development:
  uri: mongodb://admin:admin@flame.mongohq.com:27090/shapado-development
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin
  pool_size: 5
  timeout: 5
test:
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin  
  pool_size: 5
  timeout: 5  
production:
  uri: mongodb://admin:admin@flame.mongohq.com:27090/shapado-development
  database: shapado-development
  host: flame.mongohq.com
  port: 27090
  adapter: mongodb
  username: admin
  password: admin  
  pool_size: 5
  timeout: 5  