development:
  uri: mongodb://admin:admin@flame.mongohq.com:27090/shapado-development
test:
  database: shapado-test

production:
  uri: mongodb://admin:admin@flame.mongohq.com:27090/shapado-development
